// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Data;

#nullable disable

namespace backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FlashcardChoiceMultipleChoiceFlashcardAnswer", b =>
                {
                    b.Property<Guid>("AnswersForMultipleChoicecardsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelectedChoicesId")
                        .HasColumnType("uuid");

                    b.HasKey("AnswersForMultipleChoicecardsId", "SelectedChoicesId");

                    b.HasIndex("SelectedChoicesId");

                    b.ToTable("FlashcardChoiceMultipleChoiceFlashcardAnswer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.ClassYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ClassYears");
                });

            modelBuilder.Entity("backend.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IsoCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("backend.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("InviteLinkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InviteLinkId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseInstructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseInstructors");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseInviteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseInviteLinks");
                });

            modelBuilder.Entity("backend.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("backend.Domain.Entities.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactFromJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("FlashcardType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactFromJobId");

                    b.HasIndex("ContentCategoryId");

                    b.HasIndex("LectureId");

                    b.ToTable("Flashcards");

                    b.HasDiscriminator<int>("FlashcardType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uuid");

                    b.Property<int>("FlashcardType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseEnrollmentId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashCardChoiceAnswerOptions");

                    b.HasDiscriminator<int>("FlashcardType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrectAnswerForMultipleChoicecardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrectAnswerForSingleChoicecardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("MultipleChoicecardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SingleChoicecardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrectAnswerForMultipleChoicecardId");

                    b.HasIndex("CorrectAnswerForSingleChoicecardId")
                        .IsUnique();

                    b.HasIndex("MultipleChoicecardId");

                    b.HasIndex("SingleChoicecardId");

                    b.ToTable("FlashCardChoiceAnswers");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeyChoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ValueChoiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("KeyChoiceId")
                        .IsUnique();

                    b.HasIndex("ValueChoiceId")
                        .IsUnique();

                    b.ToTable("FlashCardPairAnswers");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardPairAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FlashcardAnswerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("SelectedKeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelectedValueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardAnswerId");

                    b.HasIndex("SelectedKeyId");

                    b.HasIndex("SelectedValueId");

                    b.ToTable("FlashcardPairAnswer");
                });

            modelBuilder.Entity("backend.Domain.Entities.Lecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsMainContent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.HasIndex("ResourceId");

                    b.ToTable("LectureContents");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactFromJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactFromJobId");

                    b.HasIndex("LectureId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("LectureTranscripts");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscriptKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureTranscriptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LectureTranscriptId");

                    b.ToTable("LectureTranscriptKeywords");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscriptKeywordOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureTranscriptKeywordId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("OccurrenceTime")
                        .HasColumnType("interval");

                    b.Property<string>("SurroundingText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LectureTranscriptKeywordId");

                    b.ToTable("LectureTranscriptKeywordOccurrences");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscriptTimestamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LectureTranscriptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("LectureTranscriptId");

                    b.ToTable("LectureTranscriptTimestamps");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentJobId");

                    b.ToTable("MediaProcessingJobs");

                    b.HasDiscriminator<string>("JobType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("MediaProcessingJobAttempts");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJobLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProgressPercentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.ToTable("MediaProcessingJobLogs");
                });

            modelBuilder.Entity("backend.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentResourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ThumbnailResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentResourceId");

                    b.HasIndex("ThumbnailResourceId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("backend.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("backend.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Reminder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("backend.Domain.Entities.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("backend.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassYearId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassYearId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("backend.Domain.Entities.TripDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripDescriptions");
                });

            modelBuilder.Entity("backend.Domain.Entities.FreeTextFlashCard", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.Flashcard");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("backend.Domain.Entities.MatchingFlashcard", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.Flashcard");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("backend.Domain.Entities.MultipleChoiceFlashCard", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.Flashcard");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("backend.Domain.Entities.SingleChoiceFlashCard", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.Flashcard");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("backend.Domain.Entities.TrueFalseFlashCard", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.Flashcard");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("backend.Domain.Entities.FreeTextFlashcardAnswer", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.FlashcardAnswer");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("backend.Domain.Entities.MatchingFlashcardAnswer", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.FlashcardAnswer");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("backend.Domain.Entities.MultipleChoiceFlashcardAnswer", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.FlashcardAnswer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("backend.Domain.Entities.SingleChoiceFlashcardAnswer", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.FlashcardAnswer");

                    b.Property<Guid>("SelectedChoiceId")
                        .HasColumnType("uuid");

                    b.HasIndex("SelectedChoiceId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("backend.Domain.Entities.TrueFalseFlashcardAnswer", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.FlashcardAnswer");

                    b.Property<bool>("AnswerBool")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureRelatedMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.MediaProcessingJob");

                    b.Property<Guid>("LectureContentId")
                        .HasColumnType("uuid");

                    b.HasIndex("LectureContentId");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaTranscodingMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.MediaProcessingJob");

                    b.Property<Guid>("InputResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OutputResourceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TargetBitrateKbps")
                        .HasColumnType("integer");

                    b.Property<string>("TargetFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TargetHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetWidth")
                        .HasColumnType("integer");

                    b.HasIndex("InputResourceId");

                    b.HasIndex("OutputResourceId");

                    b.HasDiscriminator().HasValue("MediaTranscoding");
                });

            modelBuilder.Entity("backend.Domain.Entities.OfficeConversionMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.MediaProcessingJob");

                    b.Property<Guid>("InputResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OutputResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("InputResourceId");

                    b.HasIndex("OutputResourceId");

                    b.ToTable("MediaProcessingJobs", t =>
                        {
                            t.Property("InputResourceId")
                                .HasColumnName("OfficeConversionMediaProcessingJob_InputResourceId");

                            t.Property("OutputResourceId")
                                .HasColumnName("OfficeConversionMediaProcessingJob_OutputResourceId");

                            t.Property("TargetFormat")
                                .HasColumnName("OfficeConversionMediaProcessingJob_TargetFormat");
                        });

                    b.HasDiscriminator().HasValue("OfficeConversion");
                });

            modelBuilder.Entity("backend.Domain.Entities.CategoryClassificationMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.LectureRelatedMediaProcessingJob");

                    b.HasDiscriminator().HasValue("CategoryClassification");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardGenerationMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.LectureRelatedMediaProcessingJob");

                    b.HasDiscriminator().HasValue("FlashcardGeneration");
                });

            modelBuilder.Entity("backend.Domain.Entities.KeywordExtractionMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.LectureRelatedMediaProcessingJob");

                    b.HasDiscriminator().HasValue("KeywordExtraction");
                });

            modelBuilder.Entity("backend.Domain.Entities.ThumbnailExtractionMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.LectureRelatedMediaProcessingJob");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OutputResourceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasIndex("OutputResourceId");

                    b.ToTable("MediaProcessingJobs", t =>
                        {
                            t.Property("OutputResourceId")
                                .HasColumnName("ThumbnailExtractionMediaProcessingJob_OutputResourceId");
                        });

                    b.HasDiscriminator().HasValue("ThumbnailExtraction");
                });

            modelBuilder.Entity("backend.Domain.Entities.TranscriptionMediaProcessingJob", b =>
                {
                    b.HasBaseType("backend.Domain.Entities.LectureRelatedMediaProcessingJob");

                    b.HasDiscriminator().HasValue("Transcription");
                });

            modelBuilder.Entity("FlashcardChoiceMultipleChoiceFlashcardAnswer", b =>
                {
                    b.HasOne("backend.Domain.Entities.MultipleChoiceFlashcardAnswer", null)
                        .WithMany()
                        .HasForeignKey("AnswersForMultipleChoicecardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.FlashcardChoice", null)
                        .WithMany()
                        .HasForeignKey("SelectedChoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlashcardChoiceMultipleChoiceFlashcardAnswer_FlashCardChoi~1");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Domain.Entities.Course", b =>
                {
                    b.HasOne("backend.Domain.Entities.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("backend.Domain.ValueObjects.Colour", "Colour", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Colour");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseCategory", b =>
                {
                    b.HasOne("backend.Domain.Entities.Lecture", "Lecture")
                        .WithMany()
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseEnrollment", b =>
                {
                    b.HasOne("backend.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.CourseInviteLink", "InviteLink")
                        .WithMany()
                        .HasForeignKey("InviteLinkId");

                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Course");

                    b.Navigation("InviteLink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseInstructor", b =>
                {
                    b.HasOne("backend.Domain.Entities.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseInviteLink", b =>
                {
                    b.HasOne("backend.Domain.Entities.Course", "Course")
                        .WithMany("InviteLinks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("backend.Domain.Entities.Destination", b =>
                {
                    b.HasOne("backend.Domain.Entities.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("backend.Domain.Entities.Flashcard", b =>
                {
                    b.HasOne("backend.Domain.Entities.MediaProcessingJob", "ArtifactFromJob")
                        .WithMany()
                        .HasForeignKey("ArtifactFromJobId");

                    b.HasOne("backend.Domain.Entities.CourseCategory", "ContentCategory")
                        .WithMany("Flashcards")
                        .HasForeignKey("ContentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Lecture", "Lecture")
                        .WithMany("Flashcards")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtifactFromJob");

                    b.Navigation("ContentCategory");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardAnswer", b =>
                {
                    b.HasOne("backend.Domain.Entities.CourseEnrollment", "CourseEnrollment")
                        .WithMany("FlashcardAnswers")
                        .HasForeignKey("CourseEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Flashcard", "Flashcard")
                        .WithMany("Answers")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEnrollment");

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardChoice", b =>
                {
                    b.HasOne("backend.Domain.Entities.MultipleChoiceFlashCard", "CorrectAnswerForMultipleChoicecard")
                        .WithMany("CorrectAnswers")
                        .HasForeignKey("CorrectAnswerForMultipleChoicecardId");

                    b.HasOne("backend.Domain.Entities.SingleChoiceFlashCard", "CorrectAnswerForSingleChoicecard")
                        .WithOne("CorrectAnswer")
                        .HasForeignKey("backend.Domain.Entities.FlashcardChoice", "CorrectAnswerForSingleChoicecardId");

                    b.HasOne("backend.Domain.Entities.MultipleChoiceFlashCard", "MultipleChoicecard")
                        .WithMany("Choices")
                        .HasForeignKey("MultipleChoicecardId");

                    b.HasOne("backend.Domain.Entities.SingleChoiceFlashCard", "SingleChoiceCard")
                        .WithMany("Choices")
                        .HasForeignKey("SingleChoicecardId");

                    b.Navigation("CorrectAnswerForMultipleChoicecard");

                    b.Navigation("CorrectAnswerForSingleChoicecard");

                    b.Navigation("MultipleChoicecard");

                    b.Navigation("SingleChoiceCard");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardPair", b =>
                {
                    b.HasOne("backend.Domain.Entities.MatchingFlashcard", "Flashcard")
                        .WithMany("Pairs")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.FlashcardChoice", "KeyChoice")
                        .WithOne("KeyForFlashcardPair")
                        .HasForeignKey("backend.Domain.Entities.FlashcardPair", "KeyChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.FlashcardChoice", "ValueChoice")
                        .WithOne("ValueForFlashcardPair")
                        .HasForeignKey("backend.Domain.Entities.FlashcardPair", "ValueChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("KeyChoice");

                    b.Navigation("ValueChoice");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardPairAnswer", b =>
                {
                    b.HasOne("backend.Domain.Entities.MatchingFlashcardAnswer", "FlashcardAnswer")
                        .WithMany("PairAnswers")
                        .HasForeignKey("FlashcardAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.FlashcardChoice", "SelectedKey")
                        .WithMany("AnswerKeyForFlashcardPairs")
                        .HasForeignKey("SelectedKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.FlashcardChoice", "SelectedValue")
                        .WithMany("AnswerValueForFlashcardPairs")
                        .HasForeignKey("SelectedValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardAnswer");

                    b.Navigation("SelectedKey");

                    b.Navigation("SelectedValue");
                });

            modelBuilder.Entity("backend.Domain.Entities.Lecture", b =>
                {
                    b.HasOne("backend.Domain.Entities.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureContent", b =>
                {
                    b.HasOne("backend.Domain.Entities.Lecture", "Lecture")
                        .WithMany("Contents")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscript", b =>
                {
                    b.HasOne("backend.Domain.Entities.MediaProcessingJob", "ArtifactFromJob")
                        .WithMany()
                        .HasForeignKey("ArtifactFromJobId");

                    b.HasOne("backend.Domain.Entities.Lecture", "Lecture")
                        .WithMany("Transcripts")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.LectureContent", "Source")
                        .WithOne("Transcript")
                        .HasForeignKey("backend.Domain.Entities.LectureTranscript", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtifactFromJob");

                    b.Navigation("Lecture");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscriptKeyword", b =>
                {
                    b.HasOne("backend.Domain.Entities.LectureTranscript", "LectureTranscript")
                        .WithMany("Keywords")
                        .HasForeignKey("LectureTranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureTranscript");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscriptKeywordOccurrence", b =>
                {
                    b.HasOne("backend.Domain.Entities.LectureTranscriptKeyword", "LectureTranscriptKeyword")
                        .WithMany("Occurrences")
                        .HasForeignKey("LectureTranscriptKeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureTranscriptKeyword");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscriptTimestamp", b =>
                {
                    b.HasOne("backend.Domain.Entities.LectureTranscript", "LectureTranscript")
                        .WithMany("Timestamps")
                        .HasForeignKey("LectureTranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureTranscript");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJob", b =>
                {
                    b.HasOne("backend.Domain.Entities.MediaProcessingJob", "ParentJob")
                        .WithMany("DependentJobs")
                        .HasForeignKey("ParentJobId");

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJobAttempt", b =>
                {
                    b.HasOne("backend.Domain.Entities.MediaProcessingJob", "Job")
                        .WithMany("Attempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJobLog", b =>
                {
                    b.HasOne("backend.Domain.Entities.MediaProcessingJobAttempt", "Attempt")
                        .WithMany("Logs")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("backend.Domain.Entities.Resource", b =>
                {
                    b.HasOne("backend.Domain.Entities.Resource", "ParentResource")
                        .WithMany("AssociatedResources")
                        .HasForeignKey("ParentResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Domain.Entities.Resource", "ThumbnailResource")
                        .WithMany()
                        .HasForeignKey("ThumbnailResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentResource");

                    b.Navigation("ThumbnailResource");
                });

            modelBuilder.Entity("backend.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("backend.Domain.Entities.TodoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("backend.Domain.Entities.TodoList", b =>
                {
                    b.OwnsOne("backend.Domain.ValueObjects.Colour", "Colour", b1 =>
                        {
                            b1.Property<Guid>("TodoListId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TodoListId");

                            b1.ToTable("TodoLists");

                            b1.WithOwner()
                                .HasForeignKey("TodoListId");
                        });

                    b.Navigation("Colour")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Domain.Entities.Trip", b =>
                {
                    b.HasOne("backend.Domain.Entities.ClassYear", "ClassYear")
                        .WithMany("Trips")
                        .HasForeignKey("ClassYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Destination", "Destination")
                        .WithMany("Trips")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassYear");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("backend.Domain.Entities.TripDescription", b =>
                {
                    b.HasOne("backend.Domain.Entities.Trip", "Trip")
                        .WithMany("DescriptionParts")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("backend.Domain.Entities.SingleChoiceFlashcardAnswer", b =>
                {
                    b.HasOne("backend.Domain.Entities.FlashcardChoice", "SelectedChoice")
                        .WithMany("AnswerForSinglecards")
                        .HasForeignKey("SelectedChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureRelatedMediaProcessingJob", b =>
                {
                    b.HasOne("backend.Domain.Entities.LectureContent", "LectureContent")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("LectureContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureContent");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaTranscodingMediaProcessingJob", b =>
                {
                    b.HasOne("backend.Domain.Entities.Resource", "InputResource")
                        .WithMany()
                        .HasForeignKey("InputResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Resource", "OutputResource")
                        .WithMany()
                        .HasForeignKey("OutputResourceId");

                    b.Navigation("InputResource");

                    b.Navigation("OutputResource");
                });

            modelBuilder.Entity("backend.Domain.Entities.OfficeConversionMediaProcessingJob", b =>
                {
                    b.HasOne("backend.Domain.Entities.Resource", "InputResource")
                        .WithMany()
                        .HasForeignKey("InputResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Resource", "OutputResource")
                        .WithMany()
                        .HasForeignKey("OutputResourceId")
                        .HasConstraintName("FK_MediaProcessingJobs_Resources_OfficeConversionMediaProcess~1");

                    b.Navigation("InputResource");

                    b.Navigation("OutputResource");
                });

            modelBuilder.Entity("backend.Domain.Entities.ThumbnailExtractionMediaProcessingJob", b =>
                {
                    b.HasOne("backend.Domain.Entities.Resource", "OutputResource")
                        .WithMany()
                        .HasForeignKey("OutputResourceId");

                    b.Navigation("OutputResource");
                });

            modelBuilder.Entity("backend.Domain.Entities.ClassYear", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("backend.Domain.Entities.Country", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("backend.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Instructors");

                    b.Navigation("InviteLinks");

                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseCategory", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("backend.Domain.Entities.CourseEnrollment", b =>
                {
                    b.Navigation("FlashcardAnswers");
                });

            modelBuilder.Entity("backend.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("backend.Domain.Entities.Flashcard", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("backend.Domain.Entities.FlashcardChoice", b =>
                {
                    b.Navigation("AnswerForSinglecards");

                    b.Navigation("AnswerKeyForFlashcardPairs");

                    b.Navigation("AnswerValueForFlashcardPairs");

                    b.Navigation("KeyForFlashcardPair");

                    b.Navigation("ValueForFlashcardPair");
                });

            modelBuilder.Entity("backend.Domain.Entities.Lecture", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Flashcards");

                    b.Navigation("Transcripts");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureContent", b =>
                {
                    b.Navigation("ProcessingJobs");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscript", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("Timestamps");
                });

            modelBuilder.Entity("backend.Domain.Entities.LectureTranscriptKeyword", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJob", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("DependentJobs");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaProcessingJobAttempt", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("backend.Domain.Entities.Resource", b =>
                {
                    b.Navigation("AssociatedResources");
                });

            modelBuilder.Entity("backend.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("backend.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("backend.Domain.Entities.Trip", b =>
                {
                    b.Navigation("DescriptionParts");
                });

            modelBuilder.Entity("backend.Domain.Entities.MatchingFlashcard", b =>
                {
                    b.Navigation("Pairs");
                });

            modelBuilder.Entity("backend.Domain.Entities.MultipleChoiceFlashCard", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("CorrectAnswers");
                });

            modelBuilder.Entity("backend.Domain.Entities.SingleChoiceFlashCard", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("CorrectAnswer")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Domain.Entities.MatchingFlashcardAnswer", b =>
                {
                    b.Navigation("PairAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
