/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as frontRouteImport } from './routes/(front)/route'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as frontIndexImport } from './routes/(front)/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AdminTripsIndexImport } from './routes/admin/trips/index'
import { Route as AdminSettingsIndexImport } from './routes/admin/settings/index'
import { Route as AdminDonationsIndexImport } from './routes/admin/donations/index'
import { Route as AdminDestinationsIndexImport } from './routes/admin/destinations/index'
import { Route as AdminCountriesIndexImport } from './routes/admin/countries/index'
import { Route as frontTakForDonationIndexImport } from './routes/(front)/tak-for-donation/index'
import { Route as frontRejserIndexImport } from './routes/(front)/rejser/index'
import { Route as frontOmOsIndexImport } from './routes/(front)/om-os/index'
import { Route as frontKontaktIndexImport } from './routes/(front)/kontakt/index'
import { Route as frontDonerIndexImport } from './routes/(front)/doner/index'
import { Route as frontRejserTripIdImport } from './routes/(front)/rejser/$tripId'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const frontRouteRoute = frontRouteImport.update({
  id: '/(front)',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const frontIndexRoute = frontIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => frontRouteRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AdminTripsIndexRoute = AdminTripsIndexImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminSettingsIndexRoute = AdminSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminDonationsIndexRoute = AdminDonationsIndexImport.update({
  id: '/donations/',
  path: '/donations/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminDestinationsIndexRoute = AdminDestinationsIndexImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCountriesIndexRoute = AdminCountriesIndexImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const frontTakForDonationIndexRoute = frontTakForDonationIndexImport.update({
  id: '/tak-for-donation/',
  path: '/tak-for-donation/',
  getParentRoute: () => frontRouteRoute,
} as any)

const frontRejserIndexRoute = frontRejserIndexImport.update({
  id: '/rejser/',
  path: '/rejser/',
  getParentRoute: () => frontRouteRoute,
} as any)

const frontOmOsIndexRoute = frontOmOsIndexImport.update({
  id: '/om-os/',
  path: '/om-os/',
  getParentRoute: () => frontRouteRoute,
} as any)

const frontKontaktIndexRoute = frontKontaktIndexImport.update({
  id: '/kontakt/',
  path: '/kontakt/',
  getParentRoute: () => frontRouteRoute,
} as any)

const frontDonerIndexRoute = frontDonerIndexImport.update({
  id: '/doner/',
  path: '/doner/',
  getParentRoute: () => frontRouteRoute,
} as any)

const frontRejserTripIdRoute = frontRejserTripIdImport.update({
  id: '/rejser/$tripId',
  path: '/rejser/$tripId',
  getParentRoute: () => frontRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(front)': {
      id: '/(front)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof frontRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthRouteImport
    }
    '/(front)/': {
      id: '/(front)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof frontIndexImport
      parentRoute: typeof frontRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/(front)/rejser/$tripId': {
      id: '/(front)/rejser/$tripId'
      path: '/rejser/$tripId'
      fullPath: '/rejser/$tripId'
      preLoaderRoute: typeof frontRejserTripIdImport
      parentRoute: typeof frontRouteImport
    }
    '/(front)/doner/': {
      id: '/(front)/doner/'
      path: '/doner'
      fullPath: '/doner'
      preLoaderRoute: typeof frontDonerIndexImport
      parentRoute: typeof frontRouteImport
    }
    '/(front)/kontakt/': {
      id: '/(front)/kontakt/'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof frontKontaktIndexImport
      parentRoute: typeof frontRouteImport
    }
    '/(front)/om-os/': {
      id: '/(front)/om-os/'
      path: '/om-os'
      fullPath: '/om-os'
      preLoaderRoute: typeof frontOmOsIndexImport
      parentRoute: typeof frontRouteImport
    }
    '/(front)/rejser/': {
      id: '/(front)/rejser/'
      path: '/rejser'
      fullPath: '/rejser'
      preLoaderRoute: typeof frontRejserIndexImport
      parentRoute: typeof frontRouteImport
    }
    '/(front)/tak-for-donation/': {
      id: '/(front)/tak-for-donation/'
      path: '/tak-for-donation'
      fullPath: '/tak-for-donation'
      preLoaderRoute: typeof frontTakForDonationIndexImport
      parentRoute: typeof frontRouteImport
    }
    '/admin/countries/': {
      id: '/admin/countries/'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AdminCountriesIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/destinations/': {
      id: '/admin/destinations/'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/donations/': {
      id: '/admin/donations/'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsIndexImport
      parentRoute: typeof AdminRouteImport
    }
  }
}

// Create and export the route tree

interface frontRouteRouteChildren {
  frontIndexRoute: typeof frontIndexRoute
  frontRejserTripIdRoute: typeof frontRejserTripIdRoute
  frontDonerIndexRoute: typeof frontDonerIndexRoute
  frontKontaktIndexRoute: typeof frontKontaktIndexRoute
  frontOmOsIndexRoute: typeof frontOmOsIndexRoute
  frontRejserIndexRoute: typeof frontRejserIndexRoute
  frontTakForDonationIndexRoute: typeof frontTakForDonationIndexRoute
}

const frontRouteRouteChildren: frontRouteRouteChildren = {
  frontIndexRoute: frontIndexRoute,
  frontRejserTripIdRoute: frontRejserTripIdRoute,
  frontDonerIndexRoute: frontDonerIndexRoute,
  frontKontaktIndexRoute: frontKontaktIndexRoute,
  frontOmOsIndexRoute: frontOmOsIndexRoute,
  frontRejserIndexRoute: frontRejserIndexRoute,
  frontTakForDonationIndexRoute: frontTakForDonationIndexRoute,
}

const frontRouteRouteWithChildren = frontRouteRoute._addFileChildren(
  frontRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCountriesIndexRoute: typeof AdminCountriesIndexRoute
  AdminDestinationsIndexRoute: typeof AdminDestinationsIndexRoute
  AdminDonationsIndexRoute: typeof AdminDonationsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCountriesIndexRoute: AdminCountriesIndexRoute,
  AdminDestinationsIndexRoute: AdminDestinationsIndexRoute,
  AdminDonationsIndexRoute: AdminDonationsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof frontIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/admin/': typeof AdminIndexRoute
  '/rejser/$tripId': typeof frontRejserTripIdRoute
  '/doner': typeof frontDonerIndexRoute
  '/kontakt': typeof frontKontaktIndexRoute
  '/om-os': typeof frontOmOsIndexRoute
  '/rejser': typeof frontRejserIndexRoute
  '/tak-for-donation': typeof frontTakForDonationIndexRoute
  '/admin/countries': typeof AdminCountriesIndexRoute
  '/admin/destinations': typeof AdminDestinationsIndexRoute
  '/admin/donations': typeof AdminDonationsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof frontIndexRoute
  '/admin': typeof AdminIndexRoute
  '/rejser/$tripId': typeof frontRejserTripIdRoute
  '/doner': typeof frontDonerIndexRoute
  '/kontakt': typeof frontKontaktIndexRoute
  '/om-os': typeof frontOmOsIndexRoute
  '/rejser': typeof frontRejserIndexRoute
  '/tak-for-donation': typeof frontTakForDonationIndexRoute
  '/admin/countries': typeof AdminCountriesIndexRoute
  '/admin/destinations': typeof AdminDestinationsIndexRoute
  '/admin/donations': typeof AdminDonationsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(front)': typeof frontRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/(front)/': typeof frontIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(front)/rejser/$tripId': typeof frontRejserTripIdRoute
  '/(front)/doner/': typeof frontDonerIndexRoute
  '/(front)/kontakt/': typeof frontKontaktIndexRoute
  '/(front)/om-os/': typeof frontOmOsIndexRoute
  '/(front)/rejser/': typeof frontRejserIndexRoute
  '/(front)/tak-for-donation/': typeof frontTakForDonationIndexRoute
  '/admin/countries/': typeof AdminCountriesIndexRoute
  '/admin/destinations/': typeof AdminDestinationsIndexRoute
  '/admin/donations/': typeof AdminDonationsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/'
    | '/rejser/$tripId'
    | '/doner'
    | '/kontakt'
    | '/om-os'
    | '/rejser'
    | '/tak-for-donation'
    | '/admin/countries'
    | '/admin/destinations'
    | '/admin/donations'
    | '/admin/settings'
    | '/admin/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/admin'
    | '/rejser/$tripId'
    | '/doner'
    | '/kontakt'
    | '/om-os'
    | '/rejser'
    | '/tak-for-donation'
    | '/admin/countries'
    | '/admin/destinations'
    | '/admin/donations'
    | '/admin/settings'
    | '/admin/trips'
  id:
    | '__root__'
    | '/(front)'
    | '/admin'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(front)/'
    | '/admin/'
    | '/(front)/rejser/$tripId'
    | '/(front)/doner/'
    | '/(front)/kontakt/'
    | '/(front)/om-os/'
    | '/(front)/rejser/'
    | '/(front)/tak-for-donation/'
    | '/admin/countries/'
    | '/admin/destinations/'
    | '/admin/donations/'
    | '/admin/settings/'
    | '/admin/trips/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  frontRouteRoute: typeof frontRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  frontRouteRoute: frontRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(front)",
        "/admin",
        "/auth"
      ]
    },
    "/(front)": {
      "filePath": "(front)/route.tsx",
      "children": [
        "/(front)/",
        "/(front)/rejser/$tripId",
        "/(front)/doner/",
        "/(front)/kontakt/",
        "/(front)/om-os/",
        "/(front)/rejser/",
        "/(front)/tak-for-donation/"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/",
        "/admin/countries/",
        "/admin/destinations/",
        "/admin/donations/",
        "/admin/settings/",
        "/admin/trips/"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx",
      "parent": "/auth"
    },
    "/(front)/": {
      "filePath": "(front)/index.tsx",
      "parent": "/(front)"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/(front)/rejser/$tripId": {
      "filePath": "(front)/rejser/$tripId.tsx",
      "parent": "/(front)"
    },
    "/(front)/doner/": {
      "filePath": "(front)/doner/index.tsx",
      "parent": "/(front)"
    },
    "/(front)/kontakt/": {
      "filePath": "(front)/kontakt/index.tsx",
      "parent": "/(front)"
    },
    "/(front)/om-os/": {
      "filePath": "(front)/om-os/index.tsx",
      "parent": "/(front)"
    },
    "/(front)/rejser/": {
      "filePath": "(front)/rejser/index.tsx",
      "parent": "/(front)"
    },
    "/(front)/tak-for-donation/": {
      "filePath": "(front)/tak-for-donation/index.tsx",
      "parent": "/(front)"
    },
    "/admin/countries/": {
      "filePath": "admin/countries/index.tsx",
      "parent": "/admin"
    },
    "/admin/destinations/": {
      "filePath": "admin/destinations/index.tsx",
      "parent": "/admin"
    },
    "/admin/donations/": {
      "filePath": "admin/donations/index.tsx",
      "parent": "/admin"
    },
    "/admin/settings/": {
      "filePath": "admin/settings/index.tsx",
      "parent": "/admin"
    },
    "/admin/trips/": {
      "filePath": "admin/trips/index.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
